find_path(AVCODEC_INCLUDE_DIR libavcodec/avcodec.h)
find_library(AVCODEC_LIBRARY NAMES avcodec)

find_path(AVFORMAT_INCLUDE_DIR libavformat/avformat.h)
find_library(AVFORMAT_LIBRARY NAMES avformat)

find_path(AVUTIL_INCLUDE_DIR libavutil/avutil.h)
find_library(AVUTIL_LIBRARY NAMES avutil)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FFmpeg DEFAULT_MSG AVCODEC_LIBRARY AVCODEC_INCLUDE_DIR AVFORMAT_LIBRARY AVFORMAT_INCLUDE_DIR AVUTIL_LIBRARY AVUTIL_INCLUDE_DIR)

if(FFMPEG_FOUND)
    set(FFMPEG_INCLUDE_DIRS ${AVCODEC_INCLUDE_DIR} ${AVFORMAT_INCLUDE_DIR} ${AVUTIL_INCLUDE_DIR})
    set(FFMPEG_LIBRARIES ${AVCODEC_LIBRARY} ${AVFORMAT_LIBRARY} ${AVUTIL_LIBRARY})
endif()

mark_as_advanced(AVCODEC_LIBRARY AVCODEC_INCLUDE_DIR AVFORMAT_LIBRARY AVFORMAT_INCLUDE_DIR AVUTIL_LIBRARY AVUTIL_INCLUDE_DIR)
